"""Add missing columns to offers table

Revision ID: 5d6669c537da
Revises: b378ae5c64bb
Create Date: 2025-04-23 09:54:34.433369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6669c537da'
down_revision = 'b378ae5c64bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveau', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('autonomie', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('poids', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dimensions', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('camera', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('portee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vitesse', sa.Integer(), nullable=True))
        batch_op.drop_column('disponibilite')
        batch_op.drop_column('nombre_personnes')
        batch_op.drop_column('date_evenement')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_expedition', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_livraison', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('numero_suivi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('adresse_livraison', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('adresse_livraison')
        batch_op.drop_column('numero_suivi')
        batch_op.drop_column('date_livraison')
        batch_op.drop_column('date_expedition')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_evenement', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('nombre_personnes', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('disponibilite', sa.INTEGER(), nullable=False))
        batch_op.drop_column('vitesse')
        batch_op.drop_column('portee')
        batch_op.drop_column('camera')
        batch_op.drop_column('dimensions')
        batch_op.drop_column('poids')
        batch_op.drop_column('autonomie')
        batch_op.drop_column('stock')
        batch_op.drop_column('niveau')

    # ### end Alembic commands ###
